server:
  port: 8071

spring:
  application:
    name: spring-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ChenYunerer/SpringCloudConfigCenter.git
  rabbitmq:
    host: 47.99.189.144
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka

# post http://localhost:8071/actuator/bus-refresh to refresh config
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh