server:
  port: 8081

spring:
  application:
    name: spring-app
  datasource:
    druid:
      url: jdbc:mysql://39.98.55.88:10030/microservice_db1?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: Qmkj@0622.
      initialSize: 5
      maxActive: 8
      minIdle: 5
      maxWait: 5000
      useUnfairLock: true
      validationQuery: select 'x'
      validationQueryTimeout: 5000
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      filters: stat, wall, slf4j
      stat-view-servlet:
        login-username: admin
        login-password: admin
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.4.205:9411
  rabbitmq:
    host: 47.99.189.144
    port: 5672
    username: guest
    password: guest
