server:
  port: 8081

spring:
  application:
    name: spring-app
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.4.205:9411
  rabbitmq:
    host: 47.99.189.144
    port: 5672
    username: guest
    password: guest
