server:
  port: 9000

spring:
  application:
    name: tx-manager
  datasource:
    druid:
      url: jdbc:mysql://39.98.55.88:10030/tx-manager?useUnicode=true&characterEncoding=UTF-8
      username: root
      password: Qmkj@0622.
      initialSize: 5
      maxActive: 8
      minIdle: 5
      maxWait: 5000
      useUnfairLock: true
      validationQuery: select 'x'
      validationQueryTimeout: 5000
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      filters: stat, wall, slf4j
      stat-view-servlet:
        login-username: admin
        login-password: admin
  redis:
    host: 47.99.189.144
    port: 6379
    jedis:
      pool:
        min-idle: 0
        max-active: 8
        max-idle: 8
        max-wait: 1ms

mybatis:
  configuration.map-underscore-to-camel-case: true
  configuration.use-generated-keys: true

tx-lcn:
  manager:
    admin-key: 123456
    port: 9001
  logger:
    enabled: false
#tx-lcn.logger.enabled=true
# TxManager Host Ip
#tx-lcn.manager.host=127.0.0.1
# 心跳检测时间(ms)
#tx-lcn.manager.heart-time=15000
# 分布式事务执行总时间
#tx-lcn.manager.dtx-time=30000
#参数延迟删除时间单位ms
#tx-lcn.message.netty.attr-delay-time=10000
#tx-lcn.manager.concurrent-level=128
# 开启日志
#tx-lcn.logger.enabled=true
#logging.level.com.codingapi=debug