server:
  port: 8084

spring:
  application:
    name: spring-ribbon
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: http://192.168.4.205:9411

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8070/eureka


logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: DEBUG
feign:
  hystrix:
    enabled: true